Repository opendatateam/udata, pull requests merged in 2018-07, with the labels that each got.

#1797 Fix checksum display on resource modal
  CHANGELOG.md
  js/front/dataset/resource-modal.vue
Labels: regression

#1801 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#1804 Allows to serve static asserts on an external CDN domain
  CHANGELOG.md
  docs/adapting-settings.md
  requirements/install.pip
  udata/frontend/__init__.py
  udata/frontend/helpers.py
  udata/settings.py
  udata/theme/__init__.py
Labels: enhancement, performance

#1808 Rework changelog for 1.5.0 release
  CHANGELOG.md
  udata/__init__.py
Labels: documentation
