Repository opendatateam/udata, pull requests merged in 2018-05, with the labels that each got.

#1636 Add missing spatial granularities translations
  CHANGELOG.md
  udata/core/spatial/translations.py
Labels: in progress

#1643 Do not send Dataset.on_save signal on linkchecking
  CHANGELOG.md
  udata/core/dataset/models.py
  udata/linkchecker/checker.py
  udata/migrations/2018-05-04-remove-userupdateddataset-activities.js
  udata/models/datetime_fields.py
  udata/tests/dataset/test_dataset_model.py
  udata/tests/test_linkchecker.py
Labels: bug, current-sprint, performance

#1644 Backport 1.3.9
  CHANGELOG.md
  js/components/activities/timeline.vue
  less/udata/cards.less
  udata/core/dataset/rdf.py
  udata/frontend/markdown.py
  udata/templates/api/oauth_authorize.html
  udata/tests/frontend/test_markdown.py
Labels: bug, current-sprint

#1646 Bad UUID 404
  CHANGELOG.md
  udata/routing.py
  udata/tests/test_routing.py
Labels: bug, current-sprint

#1647 Add missing email templates
  CHANGELOG.md
  udata/templates/mail/security/change_notice.html
  udata/templates/mail/security/change_notice.txt
  udata/templates/mail/security/confirmation_instructions.html
  udata/templates/mail/security/confirmation_instructions.txt
  udata/templates/mail/security/login_instructions.html
  udata/templates/mail/security/login_instructions.txt
Labels: bug, current-sprint

#1648 Polyfill ChildNode.remove() for IE11
  CHANGELOG.md
  js/dom-polyfills.js
  js/front/mixin.js
Labels: bug, current-sprint

#1649 Raven-js/Sentry enhancement
  CHANGELOG.md
  js/components/form/base-completer.vue
  js/error.js
  js/models/badges.js
  js/models/error.js
  js/models/me.js
  js/plugins/auth.js
  js/raven.js
  package.json
  webpack.config.js
Labels: current-sprint, enhancement

#1650 Prevent regex special chars to break the site search
  CHANGELOG.md
  js/components/site-search.vue
  js/utils.js
  specs/utils.specs.js
Labels: bug, current-sprint

#1653 Add resend confirmation email link to login screen
  CHANGELOG.md
  udata/templates/security/login_user.html
Labels: current-sprint, enhancement

#1662 Fix Firefox custom errors handling
  CHANGELOG.md
  js/error.js
Labels: bug

#1664 Fix failing test on acronym suggestion
  udata/tests/api/test_datasets_api.py
Labels: bug, current-sprint

#1623 refactoring of discussions
  js/components/discussions/message.vue
  js/components/discussions/modal.vue
  js/components/discussions/thread-create.vue
  js/components/discussions/thread.vue
  js/components/discussions/threads.vue
Labels: in progress

#1671 Fix Firefox custom errors handling, part 2
  CHANGELOG.md
  js/error.js
Labels: bug

#1672 Make the map widget customizable.
  CHANGELOG.md
  docs/adapting-settings.md
  js/components/leaflet-map.vue
  js/config.js
  udata/settings.py
  udata/templates/macros/metadata.html
Labels: current-sprint, enhancement

#1675 Upgrade to flask-restplus 0.11.0 and make use of ujson
  requirements/install.pip
  udata/api/fields.py
Labels: current-sprint, performance, update

#1676 Fix the temporal coverage facet/field querystring parsing
  CHANGELOG.md
  udata/search/fields.py
  udata/tests/test_search.py
Labels: bug, current-sprint

#1668 Apply i18n to First and Last name in registration form
  udata/auth/forms.py
Labels: bug, i18n

#1680 [Nice to have] Add map initial territory level
  docs/adapting-settings.md
  js/front/covermap/index.js
  udata/settings.py
  udata/templates/macros/metadata.html
Labels: enhancement

#1682 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#1694 Protect Resource.need_check against int value
  udata/core/dataset/models.py
  udata/tests/test_linkchecker.py
Labels: bug

#1698 Extras cleanup
  CHANGELOG.md
  udata/core/dataset/forms.py
  udata/core/discussions/forms.py
  udata/core/organization/forms.py
  udata/forms/__init__.py
  udata/forms/fields.py
  udata/tests/forms/test_extras_fields.py
  udata/tests/helpers.py
  udata/tests/test_model.py
Labels: bug, current-sprint, enhancement, refactoring

#1699 Extras parsing and improvements
  CHANGELOG.md
  udata/forms/fields.py
  udata/models/__init__.py
  udata/models/extras_fields.py
  udata/tests/forms/test_extras_fields.py
  udata/tests/test_model.py
Labels: current-sprint, enhancement, refactoring

#1700 Register known extras
  CHANGELOG.md
  udata/core/dataset/rdf.py
  udata/forms/fields.py
  udata/harvest/models.py
  udata/linkchecker/models.py
  udata/models/__init__.py
  udata/tests/forms/test_extras_fields.py
Labels: current-sprint, enhancement

#1705 Use all space available to display previews
  js/front/dataset/preview-modal.vue
  js/front/dataset/resource-modal.vue
Labels: user-interface
