Repository opendatateam/udata, pull requests merged in 2018-03, with the labels that each got.

#1467 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1470 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1462 Added link to password change into the admin
  CHANGELOG.md
  js/locales/udata.en.json
  js/views/me.vue
  udata/translations/udata.pot
Labels: enhancement, in progress, user-interface

#1468 Chunked upload support
  CHANGELOG.md
  js/components/file/uploader.vue
  js/mixins/uploader.js
  package.json
  udata/core/dataset/api.py
  udata/core/storages/__init__.py
  udata/core/storages/api.py
  udata/core/storages/utils.py
  udata/core/storages/views.py
  udata/fileutils.py
  udata/tests/api/test_datasets_api.py
  udata/tests/test_fileutils.py
  udata/tests/test_storages.py
Labels: current-sprint, enhancement, in progress, performance, quick-win-big-impacts

#1463 Drop USE_SSL
  CHANGELOG.md
  docs/adapting-settings.md
  setup.py
  udata/app.py
  udata/auth/__init__.py
  udata/auth/views.py
  udata/frontend/markdown.py
  udata/settings.py
  udata/sitemap.py
  udata/tests/frontend/test_markdown.py
  udata/tests/plugin.py
  udata/tests/test_auth.py
  udata/tests/test_sitemap.py
Labels: current-sprint, enhancement, in progress

#1473 New Crowdin translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1474 Fix organization embed
  CHANGELOG.md
  js/widgets.js
Labels: in progress

#1476 New Crowdin translations
  js/locales/udata.pt.json
Labels: in progress

#1477 Uncrop search results title
  less/udata/search.less
Labels: bug, in progress

#1478 Fix encode error on db migrate
  udata/commands/db.py
Labels: bug, current-sprint, in progress

#1479 Fix clamping
  less/udata/cards.less
  less/udata/mixins.less
  less/udata/search.less
  package.json
  udata/templates/dataset/reuse-card.html
Labels: bug, current-sprint, in progress, user-interface

#1483 Added PT Language Elasticsearch analyzer.
  udata/search/analysis.py
Labels: enhancement, i18n

#1484 High priority for sendmail tasks
  CHANGELOG.md
  udata/settings.py
Labels: in progress

#1486 Generic plugin entrypoint
  docs/extending.md
  udata/app.py
  udata/entrypoints.py
Labels: current-sprint, enhancement, in progress

#1487 Tasks routing
  CHANGELOG.md
  udata/core/organization/tasks.py
  udata/core/user/tasks.py
  udata/harvest/tasks.py
  udata/patch_flask_security.py
  udata/search/__init__.py
  udata/settings.py
  udata/tasks.py
  udata/tests/workers/test_tasks_routing.py
Labels: current-sprint, enhancement, in progress

#1488 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1475 Add security.send_confirmation template
  CHANGELOG.md
  udata/templates/security/send_confirmation.html
Labels: in progress

#1490 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1493 Upload cleanup
  js/mixins/uploader.js
  udata/core/storages/api.py
  udata/sentry.py
  udata/tests/plugin.py
  udata/tests/test_storages.py
Labels: current-sprint, enhancement, in progress

#1495 Handle chunks max retention time
  udata/core/storages/api.py
  udata/core/storages/tasks.py
  udata/settings.py
  udata/tasks.py
  udata/tests/test_storages.py
Labels: current-sprint, enhancement, in progress

#1497 Jobs commands
  CHANGELOG.md
  docs/administrative-tasks.md
  udata/core/jobs/commands.py
  udata/core/jobs/models.py
  udata/harvest/commands.py
  udata/tests/cli/test_db_cli.py
  udata/tests/helpers.py
  udata/tests/plugin.py
  udata/tests/workers/test_jobs_commands.py
Labels: current-sprint, documentation, enhancement, in progress

#1498 Document Celery over systemd instead of Celery over uWSGI
  docs/installation.md
Labels: current-sprint, documentation, in progress

#1500 fix topic pages
  udata/templates/carousel.html
  udata/templates/topic/display.html
Labels: in progress

#1501 New Crowdin translations
  js/locales/udata.pt.json
Labels: in progress

#1505 GeoZones/GeoIDs fixes
  CHANGELOG.md
  udata/core/spatial/commands.py
  udata/core/spatial/geoids.py
  udata/core/spatial/models.py
  udata/core/spatial/tests/test_geoid.py
  udata/core/spatial/tests/test_models.py
  udata/migrations/2018-03-14-geozones-validity.js
Labels: bug, current-sprint, in progress

#1506 Fix filter syntax in oauth authorize template
  CHANGELOG.md
  udata/templates/api/oauth_authorize.html
Labels: bug, current-sprint, in progress

#1507 Prevent error on site resources metric
  CHANGELOG.md
  udata/core/site/metrics.py
Labels: bug, current-sprint, in progress

#1508 Routing fixes
  CHANGELOG.md
  udata/routing.py
  udata/tests/test_routing.py
Labels: bug, current-sprint, in progress

#1509 Lazy Mongo connexion
  CHANGELOG.md
  udata/settings.py
Labels: bug, current-sprint, in progress, performance

#1510 Fix Sentry missing udata version
  CHANGELOG.md
  udata/sentry.py
Labels: bug, current-sprint, in progress

#1511 Support OAuth2 request-body credentials
  CHANGELOG.md
  udata/api/oauth2.py
  udata/tests/api/test_auth_api.py
Labels: current-sprint, enhancement, in progress

#1514 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1516 Uploads tuning
  CHANGELOG.md
  js/mixins/uploader.js
  udata/core/storages/api.py
  udata/tests/test_storages.py
Labels: bug, current-sprint

#1517 Fix OAuth2 token model
  CHANGELOG.md
  udata/api/oauth2.py
  udata/settings.py
  udata/tests/api/test_auth_api.py
Labels: bug, current-sprint, in progress

#1518 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1521 Remove territory claim banner
  CHANGELOG.md
  udata/features/territories/views.py
  udata/templates/territories/territory.html
  udata/tests/features/territories/test_territories_process.py
  udata/translations/udata.pot
Labels: in progress

#1522 New Crowdin translations
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1523 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1527 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1525 OEmbed cards
  .circleci/config.yml
  CHANGELOG.md
  js/components/buttons/integrate.vue
  js/front/reuse.js
  js/oembed.js
  less/oembed-font/fonts/oembed.svg
  less/oembed-font/fonts/oembed.ttf
  less/oembed-font/fonts/oembed.woff
  less/oembed-font/fonts/udata-oembed.svg
  less/oembed-font/fonts/udata-oembed.ttf
  less/oembed-font/fonts/udata-oembed.woff
  less/oembed-font/icomoon-udata-oembed.json
  less/oembed-font/style.less
  less/oembed-font/variables.less
  less/oembed.less
  less/udata/cards.less
  package.json
  tasks.py
  udata/api/__init__.py
  udata/app.py
  udata/features/oembed/api.py
  udata/templates/dataset/card.html
  udata/templates/dataset/display.html
  udata/templates/dataset/oembed.html
  udata/templates/macros/certified.html
  udata/templates/macros/integrate.html
  udata/templates/oembed.html
  udata/templates/reuse/card.html
  udata/templates/reuse/display.html
  udata/templates/reuse/oembed.html
  udata/tests/api/test_oembed_api.py
  udata/theme/__init__.py
  webpack.config.oembed.js
Labels: current-sprint, enhancement, in progress, refactoring, user-interface

#1530 Fixes search result vertical cut off (fix opendatalu/gouvlu#63)
  CHANGELOG.md
  less/udata/search.less
Labels: bug, in progress, user-interface

#1532 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n, in progress

#1539 Prevent visually disabled pagination buttons from being clicked
  CHANGELOG.md
  udata/templates/macros/paginator.html
Labels: bug, current-sprint, in progress

#1536 Allow external URLs in all helpers
  udata/frontend/helpers.py
Labels: current-sprint, in progress

#1537 Sort organization by name (and not title)
  CHANGELOG.md
  udata/templates/organization/list.html
Labels: bug, current-sprint, in progress

#1538 Ensure 'publish as" screen properly hide admin only widgets
  CHANGELOG.md
  js/components/widgets/publish-as.vue
Labels: bug, current-sprint, in progress

#1543 Specify font-family on cards
  less/udata/cards.less
Labels: bug, current-sprint, in progress

#1545 Adjust NGinx configuration for embeds
  docs/installation.md
Labels: current-sprint, documentation

#1546 New Crowdin translations
  js/locales/udata.pt.json
Labels: in progress

#1548 Upgrade sifter
  CHANGELOG.md
  package.json
Labels: in progress

#1550 Upgrade jquery-validation to 1.17.0 to fix some client-side validation issues
  CHANGELOG.md
  js/components/form/base-form.js
  js/form/common.js
  package.json
Labels: admin, bug, current-sprint, in progress

#1549 Apply font family to oembed container instead of cards
  CHANGELOG.md
  less/oembed.less
  less/udata/cards.less
Labels: current-sprint, in progress

#1551 Improve cli unicode handling
  CHANGELOG.md
  udata/commands/__init__.py
  udata/commands/test.py
  udata/tests/test_utils.py
  udata/utils.py
Labels: bug, in progress

#1552 Fix DCAT harvester mime detection
  CHANGELOG.md
  udata/harvest/tests/dcat/catalog.xml
  udata/harvest/tests/test_dcat_backend.py
  udata/rdf.py
  udata/tests/test_rdf.py
Labels: bug, current-sprint, harvesting, in progress
