Repository opendatateam/udata, pull requests merged in 2018-08, with the labels that each got.

#1812 Harvest config admin
  CHANGELOG.md
  js/components/form/base-field.js
  js/components/form/checkbox.vue
  js/components/form/markdown-editor.vue
  js/components/form/select-input.vue
  js/components/form/text-input.vue
  js/components/form/url-field.vue
  js/components/harvest/config-form.vue
  js/components/harvest/filter-field.vue
  js/components/harvest/form.vue
  js/models/harvest/backends.js
  js/views/harvester-edit.vue
  udata/harvest/backends/base.py
Labels: admin, current-sprint, enhancement, harvesting, user experience

#1813 New Crowdin translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#1814 Py3 merge
  .circleci/config.yml
  CHANGELOG.md
  docs/adapting-settings.md
  js/components/form/base-field.js
  js/components/form/checkbox.vue
  js/components/form/markdown-editor.vue
  js/components/form/select-input.vue
  js/components/form/text-input.vue
  js/components/form/url-field.vue
  js/components/harvest/config-form.vue
  js/components/harvest/filter-field.vue
  js/components/harvest/form.vue
  js/components/organization/card-filter.vue
  js/components/organization/pre-create.vue
  js/front/dataset/resource-modal.vue
  js/locales/udata.ar.json
  js/locales/udata.en.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
  js/models/harvest/backends.js
  js/views/harvester-edit.vue
  less/site.less
  less/udata/resource.less
  package.json
  requirements/circleci.pip
  requirements/develop.pip
  requirements/doc.pip
  requirements/install.pip
  requirements/test.pip
  udata/__init__.py
  udata/forms/fields.py
  udata/frontend/__init__.py
  udata/frontend/helpers.py
  udata/settings.py
  udata/templates/dataset/display.html
  udata/templates/dataset/resource/card.html
  udata/tests/api/test_datasets_api.py
  udata/theme/__init__.py
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
  udata/translations/udata.pot
Labels: bug, update

#1815 Ensure OEmbed works with CDN and fixes some static serialization
  CHANGELOG.md
  js/components/buttons/integrate.vue
  js/oembed.js
  js/widgets.js
  udata/frontend/helpers.py
  udata/templates/macros/integrate.html
  udata/templates/territories/territory.html
  udata/theme/__init__.py
Labels: bug, current-sprint, regression

#1821 Fix client-side temporal coverage rendering (fix etalab/data.gouv.fr#81)
  CHANGELOG.md
  js/components/dataset/filters.js
  package.json
Labels: bug, update

#1822 Prevent word breaking when wrapping discussions messages (fix #1820)
  CHANGELOG.md
  js/components/discussions/message.vue
Labels: bug, current-sprint

#1823 Fixes on issues and discussions mails
  CHANGELOG.md
  udata/core/discussions/tasks.py
  udata/core/issues/tasks.py
  udata/templates/mail/discussion_closed.html
  udata/templates/mail/discussion_closed.txt
  udata/templates/mail/issue_closed.html
  udata/templates/mail/issue_closed.txt
  udata/templates/mail/new_discussion.html
  udata/templates/mail/new_discussion.txt
  udata/templates/mail/new_discussion_comment.html
  udata/templates/mail/new_discussion_comment.txt
  udata/templates/mail/new_issue.html
  udata/templates/mail/new_issue.txt
  udata/templates/mail/new_issue_comment.html
  udata/templates/mail/new_issue_comment.txt
Labels: bug, current-sprint, enhancement, user experience

#1826 Assets manifest and long-term caching
  .gitignore
  CHANGELOG.md
  docs/creating-theme.md
  package.json
  udata/assets.py
  udata/commands/serve.py
  udata/entrypoints.py
  udata/frontend/__init__.py
  udata/frontend/helpers.py
  udata/templates/admin.html
  udata/templates/raw.html
  udata/templates/reuse/display.html
  udata/theme/__init__.py
  webpack.config.js
Labels: add-to-documentation, current-sprint, documentation, performance, refactoring, theming, user experience

#1833 Simplified date range display on cards and search results
  CHANGELOG.md
  js/components/dataset/details.vue
  js/components/dataset/filters.js
  udata/frontend/helpers.py
  udata/templates/dataset/display.html
  udata/tests/frontend/test_frontend_filters.py
Labels: enhancement, user-interface

#1832 Allows to clear dataset form temporal coverage
  CHANGELOG.md
  js/components/form/daterange-picker.vue
Labels: admin, bug, user experience

#1834 Fix missing dataset title on client-side card listing
  CHANGELOG.md
  js/components/dataset/card.vue
  js/models/base.js
  js/views/editorial.vue
Labels: admin, bug

#1837 Explicit supported python version in setup.py
  setup.py
Labels: enhancement

#1838 Prevent front views from hitting swagger.json
  CHANGELOG.md
  js/front/dataset/resource-modal.vue
Labels: performance, user experience

#1839 Switch discussion.posted_by from user ID to embedded user
  CHANGELOG.md
  js/components/discussions/message.vue
  js/components/discussions/thread.vue
  udata/core/discussions/api.py
  udata/tests/test_discussions.py
Labels: performance, refactoring

#1841 Add missing default spatial granularity (fix #1790)
  CHANGELOG.md
  udata/core/spatial/api_fields.py
Labels: bug

#1840 Ensure API doc works without data
  CHANGELOG.md
  udata/api/__init__.py
  udata/templates/apidoc.html
Labels: bug, user experience

#1846 Resources modals consistency
  CHANGELOG.md
  js/components/dataset/resource/add-modal.vue
  js/components/dataset/resource/form.vue
  js/components/dataset/resource/modal.vue
  js/components/form/markdown-editor.vue
Labels: admin, bug, user experience

#1842 Upload errors handling
  CHANGELOG.md
  js/components/alert.vue
  js/locales/udata.en.json
  js/mixins/uploader.js
Labels: admin, bug, enhancement, user experience

#1845 Ensure chunks directory is also removed on cleanup
  CHANGELOG.md
  udata/core/storages/tasks.py
  udata/tests/test_storages.py
Labels: bug

#1849 Upgrade to latest fineuploader version to benefit from bugfixes
  CHANGELOG.md
  package.json
Labels: update

#1850 New Crowdin translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
Labels: i18n

#1848 Allows to filter datasets on resource type
  CHANGELOG.md
  udata/core/dataset/search.py
  udata/templates/dataset/search-labels.html
Labels: enhancement

#1851 Backport 1.5
  CHANGELOG.md
  js/components/dataset/card.vue
  js/components/form/daterange-picker.vue
  js/components/modal.vue
  js/components/notification-zone.vue
  js/front/dataset/resource-modal.vue
  js/models/base.js
  js/views/editorial.vue
  setup.py
  udata/api/__init__.py
  udata/core/spatial/api_fields.py
  udata/templates/apidoc.html
Labels: bug

#1853 Fix missing import causing date parsing failure (fix #1369)
  CHANGELOG.md
  js/components/form/daterange-picker.vue
Labels: bug

#1852 Normalize uploaded filenames
  CHANGELOG.md
  udata/core/storages/api.py
  udata/core/storages/utils.py
  udata/tests/test_storages.py
Labels: enhancement

#1855 Use left and right arrows instead of hamburger icon for admin sidebar
  CHANGELOG.md
  js/admin.vue
  js/components/header.vue
Labels: admin, enhancement, user experience, user-interface

#1856 Merge changes from 1.5.3
  CHANGELOG.md
  js/components/dataset/resource/add-modal.vue
  js/components/dataset/resource/form.vue
  js/components/dataset/resource/modal.vue
  js/components/form/daterange-picker.vue
  js/components/form/markdown-editor.vue
  package.json
  udata/core/storages/api.py
  udata/core/storages/tasks.py
  udata/core/storages/utils.py
  udata/tests/test_storages.py
  udata/tests/test_uris.py
  udata/uris.py
Labels: bug

#1857 Posts workflow rework
  CHANGELOG.md
  js/admin.routes.js
  js/components/dataset/card.vue
  js/components/form-layout.vue
  js/components/post/content.vue
  js/components/post/form.vue
  js/components/post/list.vue
  js/components/post/publish-modal.vue
  js/components/post/unpublish-modal.vue
  js/locales/udata.en.json
  js/models/post.js
  js/views/post-edit.vue
  js/views/post.vue
  less/post.less
  udata/core/post/api.py
  udata/core/post/factories.py
  udata/core/post/forms.py
  udata/core/post/models.py
  udata/core/post/tests/test_api.py
  udata/core/post/tests/test_frontend.py
  udata/core/post/views.py
  udata/core/site/views.py
  udata/migrations/2019-06-07-posts-publication-date.js
  udata/templates/post/display.html
  udata/templates/post/search-result.html
  udata/tests/plugin.py
  udata/translations/udata.pot
Labels: admin, enhancement, refactoring, user experience

#1860 Py3 alpine based build
  .circleci/config.yml
  requirements/circleci.pip
Labels: build
