Repository opendatateam/udata, pull requests merged in 2018-04, with the labels that each got.

#1554 Add the missing harvester URL in admin
  CHANGELOG.md
  js/components/harvest/source.vue
  js/views/harvester-edit.vue
  js/views/harvester.vue
Labels: admin, bug, current-sprint, harvesting, in progress

#1553 Fix harvester job/preview layout
  CHANGELOG.md
  js/components/datatable/widget.vue
  js/components/harvest/job.vue
  js/components/harvest/preview.vue
Labels: admin, bug, current-sprint, in progress, user-interface

#1555 Fix some search unicode issues
  CHANGELOG.md
  udata/search/fields.py
  udata/tests/test_search.py
Labels: bug, current-sprint, in progress

#1556 Small fixes on OEmbed URL detection
  CHANGELOG.md
  udata/features/oembed/api.py
  udata/tests/api/test_oembed_api.py
Labels: bug, current-sprint

#1560 Use nb_hits instead of views to count downloads
  CHANGELOG.md
  js/components/dataset/resource/list.vue
Labels: in progress

#1561 Prevent XSS in search on TermFacets (Fix OBB-595082)
  CHANGELOG.md
  udata/frontend/views.py
  udata/search/__init__.py
  udata/search/fields.py
  udata/search/views.py
  udata/tests/frontend/test_search_frontend.py
  udata/tests/test_search.py
  udata/utils.py
Labels: bug, current-sprint, in progress, security

#1562 Fix breadcrumb bar layout on empty search
  CHANGELOG.md
  less/udata/search.less
Labels: bug, current-sprint, in progress, user-interface

#1563 Normalize resource.format
  CHANGELOG.md
  udata/core/dataset/forms.py
  udata/migrations/2018-04-03-normalize-resource-format.js
  udata/tests/api/test_datasets_api.py
Labels: in progress

#1435 Typed resources
  CHANGELOG.md
  js/components/dataset/filters.js
  js/components/dataset/resource/api-form.vue
  js/components/dataset/resource/file-form.vue
  js/components/dataset/resource/form.vue
  js/components/dataset/resource/list.vue
  js/components/dataset/resource/modal.vue
  js/components/dataset/resource/remote-form.vue
  js/front/dataset/index.js
  js/mixins/uploader.js
  js/models/resource_types.js
  js/views/community-resource-wizard.vue
  less/udata/resource.less
  udata/core/dataset/api.py
  udata/core/dataset/api_fields.py
  udata/core/dataset/factories.py
  udata/core/dataset/forms.py
  udata/core/dataset/models.py
  udata/core/dataset/views.py
  udata/frontend/helpers.py
  udata/migrations/2018-02-13-migrate-resources-api-filetype.js
  udata/templates/dataset/display.html
  udata/tests/api/test_datasets_api.py
Labels: in progress

#1569 Prevent cards style to be styled by bootstrap 4
  CHANGELOG.md
  less/oembed.less
  less/udata/cards.less
Labels: admin, archive, bug, current-sprint, in progress

#1567 Enforce a domain whitelist when resource.filetype is file
  CHANGELOG.md
  docs/adapting-settings.md
  udata/core/dataset/forms.py
  udata/core/dataset/models.py
  udata/models/url_field.py
  udata/settings.py
  udata/tests/api/test_datasets_api.py
Labels: current-sprint, in progress

#1571 Feature/dynamic api doc
  CHANGELOG.md
  udata/api/__init__.py
  udata/templates/apidoc.html
Labels: documentation

#1531 Resource cards (take 2)
  js/front/dataset/index.js
  js/front/dataset/resource-modal.vue
  js/front/dataset/resource/availability.vue
  js/front/mixin.js
  js/plugins/clipboard.js
  less/site.less
  less/udata/community.less
  less/udata/resource.less
  less/udata/variables.less
  package.json
  udata/frontend/helpers.py
  udata/templates/dataset/display.html
  udata/templates/dataset/resource/card.html
  udata/templates/dataset/resource/list-item.html
Labels: current-sprint, in progress

#1572 Upgrade to authlib 0.6
  requirements/install.pip
  udata/api/oauth2.py
  udata/tests/api/test_auth_api.py
Labels: update

#1570 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1576 Fix organizations sort by last_modified
  CHANGELOG.md
  udata/core/organization/search.py
Labels: bug, in progress

#1575 New Crowdin translations
  udata/translations/ar/LC_MESSAGES/udata.po
Labels: in progress

#1579 Display dataset recommendations from udata-recommendations
  udata/frontend/__init__.py
  udata/models/extras_fields.py
  udata/templates/dataset/display.html
Labels: current-sprint, in progress

#1581 Added resource.preview_url and display it (fix #1564)
  CHANGELOG.md
  docs/adapting-settings.md
  js/front/dataset/index.js
  js/front/dataset/preview-modal.vue
  udata/core/dataset/api_fields.py
  udata/core/dataset/forms.py
  udata/core/dataset/models.py
  udata/core/dataset/views.py
  udata/settings.py
  udata/templates/dataset/resource/card.html
Labels: current-sprint, enhancement, in progress, quick-win-big-impacts

#1584 Fix dataset creation form (and any form by the way)
  CHANGELOG.md
  js/components/form/base-field.js
  js/components/form/daterange-picker.vue
  js/components/form/horizontal-field.vue
  js/components/form/vertical-field.vue
Labels: bug, current-sprint, in progress

#1585 Fix client-side markdown rendering XSS
  CHANGELOG.md
  js/helpers/commonmark.js
Labels: bug, current-sprint, in progress, security

#1583 Prepare for legacy PyPI closure and PyPI warehouse supporting markdown
  .circleci/config.yml
  CHANGELOG.md
  docs/creating-theme.md
  docs/testing-code.md
  docs/versionning.md
  setup.py
  udata/templates/footer.html
Labels: current-sprint, in progress

#1590 Merge 1.3.6
  .circleci/config.yml
  CHANGELOG.md
  docs/adapting-settings.md
  js/components/form/base-field.js
  js/components/form/daterange-picker.vue
  js/components/form/horizontal-field.vue
  js/components/form/vertical-field.vue
  js/helpers/commonmark.js
  less/oembed.less
  less/udata/cards.less
  requirements/install.pip
  udata/core/organization/search.py
  udata/forms/fields.py
  udata/harvest/filters.py
  udata/harvest/tests/test_filters.py
  udata/models/url_field.py
  udata/settings.py
  udata/tests/test_model.py
  udata/tests/test_uris.py
  udata/uris.py
Labels: current-sprint, in progress

#1593 New Crowdin translations
  js/locales/udata.ar.json
Labels: in progress

#1592 Extra license fields
  CHANGELOG.md
  udata/core/dataset/models.py
  udata/tests/dataset/test_dataset_model.py
Labels: current-sprint, enhancement, in progress

#1596 Unpin tlds package
  requirements/install.pip
Labels: in progress

#1547 Resource modals: use API call
  .gitignore
  CHANGELOG.md
  js/components/dataset/resource/modal.vue
  js/front/dataset/index.js
  js/front/dataset/resource-modal.vue
  js/front/dataset/resource/availability.vue
  js/models/resource.js
  udata/core/dataset/api.py
  udata/core/dataset/models.py
  udata/templates/dataset/resource/card.html
  udata/tests/api/test_datasets_api.py
Labels: current-sprint, enhancement

#1597 Bring back resources list title margins
  less/udata/resource.less
  udata/templates/dataset/display.html
Labels: in progress

#1598 Fix dataset card (resource card regression)
  less/udata/resource.less
Labels: in progress

#1599 Support protocol-relative URLs
  CHANGELOG.md
  udata/tests/test_uris.py
  udata/uris.py
Labels: current-sprint, enhancement, in progress

#1600 Display the preview URL field in the admin resource form
  js/components/dataset/resource/form.vue
Labels: current-sprint, enhancement, in progress

#1601 Fix some search parameters validation
  CHANGELOG.md
  udata/search/fields.py
  udata/tests/test_search.py
Labels: bug, current-sprint, in progress

#1602 Fix uncode API tracking
  CHANGELOG.md
  udata/api/__init__.py
Labels: bug, current-sprint, in progress

#1606 Fix concurrent upload race condition
  CHANGELOG.md
  requirements/install.pip
Labels: bug, current-sprint, in progress

#1603 Disallow resources dict in API
  CHANGELOG.md
  udata/forms/fields.py
  udata/tests/api/test_datasets_api.py
Labels: in progress

#1611 Test and fix territories routing
  .circleci/config.yml
  CHANGELOG.md
  udata/core/spatial/models.py
  udata/routing.py
  udata/tests/test_routing.py
Labels: bug, current-sprint, in progress

#1609 New Crowdin translations
  js/locales/udata.ar.json
Labels: in progress

#1607 Audience metrics: use only `views`
  CHANGELOG.md
  js/components/dataset/resource/list.vue
  js/views/organization.vue
Labels: in progress

#1613 Raise 404 on RDF unknown format
  CHANGELOG.md
  udata/core/site/rdf.py
  udata/rdf.py
  udata/tests/site/test_site_rdf.py
Labels: bug, current-sprint, in progress

#1614 Ensure current theme is available to macros requiring it in mails
  CHANGELOG.md
  udata/templates/mail/membership_request.html
  udata/templates/mail/new_follower.html
  udata/templates/mail/new_follower_org.html
  udata/templates/mail/new_reuse.html
Labels: bug, current-sprint, in progress

#1615 Fix documentation on NGinx proxy pass headers
  CHANGELOG.md
  docs/installation.md
Labels: bug, current-sprint, documentation, in progress

#1616 Remove unwanted commas in default SECURITY_EMAIL_SUBJECT_* parameters
  CHANGELOG.md
  udata/settings.py
Labels: bug, current-sprint, in progress

#1618 Make it easier to read sentry configuration
  docs/adapting-settings.md
  udata/sentry.py
  udata/settings.py
Labels: documentation, in progress

#1620 Fix sendmail regression
  CHANGELOG.md
  udata/patch_flask_security.py
Labels: in progress

#1622 Merge 1.3.8
  CHANGELOG.md
  udata/patch_flask_security.py
Labels: in progress

#1624 Fix OAuth authorization screen failing with unicode SITE_TITLE
  CHANGELOG.md
  udata/templates/api/oauth_authorize.html
Labels: bug, current-sprint, in progress

#1625 Test and fix html to markdown
  CHANGELOG.md
  udata/core/dataset/rdf.py
  udata/frontend/markdown.py
  udata/tests/frontend/test_markdown.py
Labels: current-sprint

#1632 Preview plugin
  CHANGELOG.md
  docs/administrative-tasks.md
  docs/extending.md
  udata/core/dataset/api_fields.py
  udata/core/dataset/forms.py
  udata/core/dataset/models.py
  udata/core/dataset/preview.py
  udata/entrypoints.py
  udata/tests/dataset/test_dataset_model.py
  udata/tests/dataset/test_resource_preview.py
Labels: current-sprint, enhancement, in progress, refactoring
