Repository opendatateam/udata, pull requests merged in 2018-02, with the labels that each got.

#1431 More entrypoints
  CHANGELOG.md
  docs/extending.md
  mkdocs.yml
  requirements/test.pip
  setup.py
  udata/api/__init__.py
  udata/app.py
  udata/commands/__init__.py
  udata/commands/db.py
  udata/commands/info.py
  udata/core/activity/__init__.py
  udata/core/metrics/__init__.py
  udata/core/metrics/commands.py
  udata/entrypoints.py
  udata/features/notifications/__init__.py
  udata/frontend/__init__.py
  udata/harvest/actions.py
  udata/harvest/backends/__init__.py
  udata/harvest/backends/dcat.py
  udata/harvest/tasks.py
  udata/harvest/tests/test_dcat_backend.py
  udata/i18n.py
  udata/linkchecker/backends.py
  udata/models/__init__.py
  udata/sentry.py
  udata/tasks.py
  udata/tests/plugin.py
Labels: current-sprint, documentation, enhancement, in progress, refactoring

#1432 Markdown soft breaks as new lines and client-side security
  CHANGELOG.md
  js/config.js
  js/helpers/commonmark.js
  js/plugins/markdown.js
  specs/loader.js
  specs/plugins/markdown.specs.js
  specs/polyfills/dom.js
  udata/frontend/markdown.py
  udata/templates/macros/metadata.html
  udata/tests/frontend/test_markdown.py
Labels: bug, current-sprint, enhancement, in progress

#1439 Fix missing Markdown config url encoding
  udata/templates/macros/metadata.html
Labels: bug, current-sprint, in progress

#1383 Make cards consistent again
  CHANGELOG.md
  js/components/dataset/card-list.vue
  js/components/dataset/card.vue
  js/components/organization/card.vue
  js/components/reuse/card-list.vue
  js/components/reuse/card.vue
  js/components/user/card.vue
  js/components/widgets/publish-as.vue
  js/views/reuse.vue
  js/views/topic.vue
  less/site.less
  less/udata/cards.less
  less/udata/mixins.less
  less/udata/resource.less
  less/udata/variables.less
  udata/core/organization/views.py
  udata/core/reuse/api_fields.py
  udata/core/topic/api.py
  udata/frontend/helpers.py
  udata/templates/dataset/card.html
  udata/templates/dataset/display.html
  udata/templates/home.html
  udata/templates/organization/card.html
  udata/templates/organization/display.html
  udata/templates/reuse/card.html
  udata/templates/reuse/display.html
  udata/templates/search.html
  udata/templates/topic/display.html
  udata/templates/user/card.html
  udata/templates/user/datasets.html
  udata/templates/user/following.html
  udata/templates/user/list.html
  udata/templates/user/reuses.html
Labels: current-sprint, in progress

#1440 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1441 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#1442 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n, in progress

#1434 Switch to Authlib
  CHANGELOG.md
  requirements/install.pip
  requirements/test.pip
  setup.cfg
  udata/api/oauth2.py
  udata/core/user/factories.py
  udata/migrations/2018-02-12-authlib.js
  udata/settings.py
  udata/templates/api/oauth_authorize.html
  udata/tests/api/test_auth_api.py
  udata/tests/plugin.py
Labels: bug, current-sprint, enhancement, in progress, update

#1448 Fix search API failing on unicode queries
  udata/search/adapter.py
  udata/tests/api/test_datasets_api.py
  udata/tests/test_search.py
Labels: bug, current-sprint, in progress

#1443 Fix Markdown sanitization
  js/helpers/commonmark.js
  specs/plugins/markdown.specs.js
  specs/polyfills/dom.js
Labels: bug, current-sprint, in progress

#1450 Fix authlib migration
  udata/migrations/2018-02-12-authlib.js
Labels: bug, current-sprint, in progress

#1445 New Crowdin translations
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1451 Test, fix and improve db unrecord command
  udata/commands/db.py
  udata/tests/cli/test_cli_base.py
  udata/tests/cli/test_db_cli.py
Labels: bug, current-sprint, in progress

#1452 Fix unicode handling in various query API
  CHANGELOG.md
  udata/core/reuse/factories.py
  udata/core/spatial/api.py
  udata/core/spatial/tests/test_api.py
  udata/core/tags/api.py
  udata/core/user/api.py
  udata/features/territories/api.py
  udata/tests/api/test_me_api.py
  udata/tests/api/test_tags_api.py
  udata/tests/features/territories/test_territories_api.py
Labels: bug, current-sprint, in progress

#1453 Added frontend marker and theme unloading for testing
  udata/tests/plugin.py
Labels: enhancement, in progress

#1456 Ensure app context is always here when accessing current_theme
  udata/tests/plugin.py
Labels: in progress

#1454 Extract new translatable strings
  js/locales/udata.en.json
  udata/translations/udata.pot
Labels: i18n, in progress

#1457 New Crowdin translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1458 I18n fixes
  udata/core/spatial/api.py
  udata/templates/discussion/item.html
  udata/templates/discussion/threads.html
  udata/templates/organization/card.html
  udata/templates/organization/display.html
  udata/templates/organization/search-result.html
  udata/templates/reuse/card.html
  udata/templates/reuse/search-result.html
  udata/templates/user/reuses.html
  udata/translations/udata.pot
Labels: current-sprint, i18n, in progress

#1459 New Crowdin translations
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1460 Cards tuning
  CHANGELOG.md
  js/components/dataset/card-list.vue
  js/components/dataset/card.vue
  js/components/dataset/cards-form.vue
  js/components/harvest/item.vue
  js/components/organization/card-filter.vue
  js/components/organization/card.vue
  js/components/organization/pre-create.vue
  js/components/reuse/card-list.vue
  js/components/reuse/card.vue
  js/components/reuse/cards-form.vue
  js/components/user/card-filter.vue
  js/components/user/card.vue
  js/components/widgets/publish-as.vue
  less/admin/cards.less
  less/admin/variables.less
  less/site.less
  less/udata/cards.less
  less/udata/modal.less
  less/udata/variables.less
  udata/templates/dataset/add-reuse-card.html
  udata/templates/dataset/card.html
  udata/templates/dataset/display.html
  udata/templates/organization/card.html
  udata/templates/reuse/card.html
  udata/templates/user/card.html
Labels: bug, current-sprint, enhancement, in progress, theming, user-interface

#1464 New Crowdin translations
  js/locales/udata.pt.json
Labels: in progress

#1465 New Crowdin translations
  js/locales/udata.pt.json
Labels: in progress
