Repository opendatateam/udata, pull requests merged in 2018-10, with the labels that each got.

#1904 Fix dataset follower route in admin (client)
  js/models/followers.js
Labels: bug

#1905 Remove the now useless FollowPage js model
  js/models/followers.js
  js/views/dataset.vue
  js/views/organization.vue
  js/views/reuse.vue
Labels: bug

#1908 Allows arguments in @connect decorator
  CHANGELOG.md
  udata/tasks.py
Labels: enhancement

#1909 Update translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#1914 Fix form events not bubbling (and harvester config being hidden)
  CHANGELOG.md
  js/components/form/base-field.js
  js/components/form/base-form.js
  js/components/harvest/form.vue
Labels: admin, bug

#1921 Display the owner/organization on the harvester view
  CHANGELOG.md
  js/components/harvest/source.vue
  js/components/harvest/sources.vue
  js/helpers/placeholders.js
  js/plugins/util.js
Labels: enhancement

#1920 Split harvest exceptions
  CHANGELOG.md
  udata/harvest/backends/base.py
  udata/harvest/exceptions.py
Labels: enhancement, harvesting

#1919 Prevent unicode errors on RDF URLs parsing
  CHANGELOG.md
  udata/core/dataset/rdf.py
Labels: bug, harvesting

#1918 Fix some external assets handling cases
  CHANGELOG.md
  udata/assets.py
  udata/frontend/helpers.py
  udata/theme/__init__.py
Labels: bug

#1929 Tiny fix: display the list items properly
  docs/installation.md
Labels: documentation

#1925 Ensure image picker only allows image files
  CHANGELOG.md
  js/components/widgets/image-picker.vue
  js/components/widgets/thumbnailer.vue
  js/mixins/uploader.js
  udata/core/storages/api.py
Labels: bug

#1935 Tags config
  CHANGELOG.md
  js/config.js
  udata/settings.py
  udata/tags.py
  udata/templates/macros/metadata.html
  udata/tests/api/test_tags_api.py
  udata/tests/test_tags.py
Labels: admin, bug, enhancement

#1937 Prevent error on focus in calendar
  CHANGELOG.md
  js/components/calendar.vue
Labels: admin, bug
