Repository opendatateam/udata, pull requests merged in 2018-06, with the labels that each got.

#1709 Fix missing css on front pages
  CHANGELOG.md
  js/front/covermap/index.js
  js/front/dataset/index.js
  js/front/organization/index.js
  js/front/reuse.js
  js/front/search.js
  js/front/site.js
  js/front/topic.js
  js/front/user.js
  less/front/covermap.less
  less/front/dataset.less
  less/front/organization.less
  less/front/reuse.less
  less/front/search.less
  less/front/site.less
  less/front/topic.less
  less/front/user.less
Labels: bug, user-interface

#1710 Fix missing search import
  udata/api/__init__.py
Labels: bug

#1708 Make the preview fill the modal body
  js/front/dataset/preview-modal.vue
Labels: user-interface

#1717 Make "Main file" translatable
  udata/core/dataset/models.py
Labels: bug, current-sprint, i18n

#1715 migrate harvest tests to pytest
  udata/harvest/tests/test_actions.py
  udata/harvest/tests/test_api.py
  udata/harvest/tests/test_filters.py
  udata/harvest/tests/test_models.py
  udata/harvest/tests/test_notifications.py
  udata/harvest/tests/test_tasks.py
  udata/tests/plugin.py
Labels: current-sprint, in progress, refactoring

#1716 Harvest config backend
  CHANGELOG.md
  udata/forms/fields.py
  udata/harvest/actions.py
  udata/harvest/api.py
  udata/harvest/backends/__init__.py
  udata/harvest/backends/base.py
  udata/harvest/forms.py
  udata/harvest/tests/factories.py
  udata/harvest/tests/test_actions.py
  udata/harvest/tests/test_api.py
  udata/harvest/tests/test_base_backend.py
  udata/tests/forms/test_dict_field.py
Labels: current-sprint, enhancement, in progress

#1721 add responsiveness and clean markup to resource cards
  less/udata/resource.less
  udata/templates/dataset/resource/card.html
Labels: in progress

#1725 [wip] discussions: fix bugs before 1.4 release
  js/components/discussions/thread-create.vue
  js/components/discussions/threads.vue
Labels: in progress

#1729 Prepare the changelog for 1.4 release
  CHANGELOG.md
Labels: current-sprint, documentation, in progress, update

#1736 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: in progress

#1734 Delete dataset reference in community resource when deleted
  udata/core/dataset/models.py
  udata/migrations/2018-06-07-community-resources-remove-references-to-deleted-datasets.js
  udata/tests/dataset/test_dataset_model.py
Labels: bug, in progress

#1733 Fix community resource creation and display
  CHANGELOG.md
  js/front/dataset/index.js
  js/front/dataset/resource-modal.vue
  js/views/community-resource-wizard.vue
  udata/templates/dataset/display.html
Labels: bug, in progress

#1742 Failsafe JS cache storage
  CHANGELOG.md
  js/cache.js
  js/components/site-search.vue
  specs/cache.specs.js
Labels: bug

#1743 Prevent errors on dataless JS API errors
  CHANGELOG.md
  js/plugins/api.js
Labels: bug

#1745 Cleaner harvest validation error messages
  CHANGELOG.md
  udata/harvest/backends/base.py
  udata/harvest/tests/test_base_backend.py
Labels: bug, harvesting, user experience

#1748 Can parse iso datetime in daterange
  CHANGELOG.md
  udata/tests/test_utils.py
  udata/utils.py
Labels: bug

#1756 Fix images upload
  CHANGELOG.md
  js/components/dataset/resource/form.vue
  js/components/widgets/image-picker.vue
  js/mixins/uploader.js
Labels: bug

#1769 Python 3 backports
  CHANGELOG.md
  udata/core/dataset/forms.py
  udata/core/dataset/search.py
  udata/core/dataset/views.py
  udata/core/discussions/tasks.py
  udata/core/issues/tasks.py
  udata/core/jobs/commands.py
  udata/core/spatial/search.py
  udata/frontend/markdown.py
  udata/search/fields.py
  udata/settings.py
  udata/tests/api/test_datasets_api.py
  udata/tests/frontend/__init__.py
  udata/tests/frontend/test_frontend_filters.py
  udata/tests/helpers.py
  udata/tests/test_discussions.py
  udata/tests/test_i18n.py
  udata/tests/test_issues.py
  udata/tests/test_routing.py
  udata/tests/workers/test_jobs_commands.py
Labels: bug, enhancement, refactoring

#1771 Slug redirections
  CHANGELOG.md
  udata/core/dataset/models.py
  udata/core/organization/models.py
  udata/core/post/models.py
  udata/core/reuse/models.py
  udata/core/topic/models.py
  udata/models/slug_fields.py
  udata/routing.py
  udata/tests/test_model.py
  udata/tests/test_routing.py
Labels: enhancement
