Repository opendatateam/udata, pull requests merged in 2019-03, with the labels that each got.

#2054 Remove lots of deprecation warnings
  udata/api/__init__.py
  udata/core/activity/api.py
  udata/core/dataset/api.py
  udata/core/dataset/forms.py
  udata/core/discussions/api.py
  udata/core/discussions/forms.py
  udata/core/followers/api.py
  udata/core/issues/api.py
  udata/core/issues/forms.py
  udata/core/jobs/api.py
  udata/core/jobs/forms.py
  udata/core/organization/api.py
  udata/core/organization/forms.py
  udata/core/post/forms.py
  udata/core/reuse/api.py
  udata/core/reuse/forms.py
  udata/core/site/forms.py
  udata/core/tags/api.py
  udata/core/topic/forms.py
  udata/core/user/api.py
  udata/core/user/forms.py
  udata/features/oembed/api.py
  udata/features/territories/api.py
  udata/forms/fields.py
  udata/frontend/helpers.py
  udata/harvest/api.py
  udata/harvest/forms.py
  udata/tests/api/test_auth_api.py
  udata/tests/api/test_base_api.py
  udata/tests/api/test_swagger.py
  udata/tests/api/test_user_api.py
  udata/tests/forms/test_form_field.py
  udata/tests/forms/test_nested_model_list_field.py
  udata/tests/frontend/test_dataset_frontend.py
  udata/tests/frontend/test_organization_frontend.py
  udata/tests/frontend/test_reuse_frontend.py
  udata/tests/frontend/test_user_frontend.py
  udata/tests/test_linkchecker.py
Labels: bug

#2055 Add Serbian translation strings
  js/locales/udata.sr.json
  udata/settings.py
  udata/theme/default/static/img/flags/sr.png
  udata/translations/sr/LC_MESSAGES/udata.po
  webpack.config.js
Labels: i18n

#2057 New Crowdin translations
  js/locales/udata.sr.json
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/sr/LC_MESSAGES/udata.po
Labels: i18n

#2058 Automatically loads plugin default settings
  CHANGELOG.md
  docs/extending.md
  udata/app.py
  udata/settings.py
Labels: enhancement

#2070 Fix reindex memory leaks
  CHANGELOG.md
  udata/models/slug_fields.py
  udata/search/commands.py
Labels: performance

#2074 Prevent ExtrasField failure on null value
  CHANGELOG.md
  udata/forms/fields.py
  udata/tests/forms/test_extras_fields.py
Labels: bug

#2075 Improve ModelField errors
  CHANGELOG.md
  udata/forms/fields.py
  udata/models/__init__.py
  udata/tests/forms/test_model_field.py
Labels: api, bug, user experience

#2060 New Crowdin translations
  js/locales/udata.sr.json
  udata/translations/sr/LC_MESSAGES/udata.po
Labels: i18n

#2081 Pin werkzeug==0.14.1
  CHANGELOG.md
  requirements/install.pip
Labels: bug, build, performance, update

#2072 fix topics responsivness
  CHANGELOG.md
  udata/templates/topic/display.html
Labels: bug, user-interface

#2076 Prevent client-side error on unparseable API response
  CHANGELOG.md
  js/admin.vue
Labels: admin, bug

#2077 Fix territories home map
  CHANGELOG.md
  udata/templates/territories/home.html
Labels: bug, regression, user experience

#2083 Fix the `udata job schedule` erroneous help message
  CHANGELOG.md
  udata/core/jobs/commands.py
Labels: bug

#2085 Fix upload button on replace resource file
  CHANGELOG.md
  js/components/dataset/resource/form.vue
Labels: bug

#2089 Fix harvest job status update
  CHANGELOG.md
  udata/harvest/backends/base.py
  udata/harvest/tasks.py
Labels: admin, bug, harvesting
