Repository opendatateam/udata, pull requests merged in 2019-02, with the labels that each got.

#2013 Search wording and icons consistency
  CHANGELOG.md
  udata/templates/dataset/list.html
  udata/templates/dataset/search-result.html
  udata/templates/macros/search.html
  udata/templates/organization/search-result.html
  udata/templates/reuse/search-result.html
Labels: search, user-interface

#2014 Switch search facets clear action to a "by term" approach
  CHANGELOG.md
  less/udata/search.less
  udata/templates/macros/search.html
Labels: search, user experience, user-interface

#2012 Ensures all modals have the same buttons styles and orders
  CHANGELOG.md
  js/components/badges/modal.vue
  js/components/dataset/delete-modal.vue
  js/components/dataset/resource/add-modal.vue
  js/components/dataset/resource/modal.vue
  js/components/discussions/modal.vue
  js/components/harvest/delete-modal.vue
  js/components/harvest/schedule-modal.vue
  js/components/issues/modal.vue
  js/components/organization/delete-modal.vue
  js/components/post/delete-modal.vue
  js/components/reuse/delete-modal.vue
  js/components/topic/delete-modal.vue
  js/components/transfer/request-modal.vue
  js/components/transfer/response-modal.vue
  js/components/user/delete-me-modal.vue
  js/components/user/delete-user-modal.vue
Labels: admin, enhancement, user experience

#2017 Considered CDN_DOMAIN as valid and ensure error message is localized
  CHANGELOG.md
  udata/core/dataset/forms.py
  udata/translations/udata.pot
Labels: bug

#2023 Bugfix/typos
  CHANGELOG.md
  CONTRIBUTING.md
  docs/adapting-settings.md
  docs/administrative-tasks.md
  docs/creating-theme.md
  docs/development-environment.md
  docs/docker-deployment.md
  docs/extending.md
  docs/harvesting.md
  docs/installation.md
  docs/rdf.md
  docs/system-dependencies.md
  docs/testing-code.md
  docs/versioning.md
  js/admin.vue
  js/cache.js
  js/components/datatable/row.vue
  js/components/form/base-form.js
  js/components/popover.vue
  js/models/badges.js
  js/models/base.js
  js/plugins/api.js
  js/plugins/auth.js
  js/utils.js
  mkdocs.yml
  specs/components/form/base.specs.js
  specs/mocks/udata-swagger.json
  specs/udata.json
  specs/udata.swagger.json
  udata/api/__init__.py
  udata/commands/__init__.py
  udata/core/dataset/api_fields.py
  udata/core/dataset/forms.py
  udata/core/discussions/api.py
  udata/core/issues/api.py
  udata/core/post/api.py
  udata/features/territories/views.py
  udata/features/transfer/api.py
  udata/frontend/__init__.py
  udata/harvest/api.py
  udata/harvest/forms.py
  udata/i18n.py
  udata/routing.py
  udata/search/commands.py
  udata/search/query.py
  udata/tests/__init__.py
  udata/tests/helpers.py
  udata/tests/test_routing.py
  udata/translations/ar/LC_MESSAGES/udata.po
  udata/translations/es/LC_MESSAGES/udata.po
  udata/translations/fr/LC_MESSAGES/udata.po
  udata/translations/pt/LC_MESSAGES/udata.po
  udata/translations/sr/LC_MESSAGES/udata.po
  udata/utils.py
Labels: documentation

#2045 Discussion and issue form fix
  CHANGELOG.md
  js/components/discussions/modal.vue
  js/components/issues/modal.vue
Labels: bug

#2047 New Crowdin translations
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#2050 Pin highlight.js to 9.14.2
  package.json
Labels: bug, build

#2048 Fixes SlugField with no_dereference
  CHANGELOG.md
  udata/models/slug_fields.py
Labels: bug

#2049 Ensure deleted user slug is pseudonymized too (fix #2016)
  CHANGELOG.md
  udata/core/organization/factories.py
  udata/core/user/models.py
  udata/core/user/tests/test_user_model.py
  udata/tests/api/test_user_api.py
Labels: bug

#2052 Prevent the "Add resource" modal from closing when using the frontend "Add resource" button
  CHANGELOG.md
  js/components/dataset/resource/add-modal.vue
Labels: admin, bug, user experience
