Repository opendatateam/udata, pull requests merged in 2019-10, with the labels that each got.

#2323 Hooks
  CHANGELOG.md
  docs/extending.md
  udata/app.py
  udata/frontend/__init__.py
  udata/templates/dataset/display.html
  udata/templates/raw.html
  udata/tests/frontend/test_hooks.py
Labels: enhancement

#2335 Py3 apply updates
  .circleci/config.yml
  requirements/circleci.pip
  requirements/develop.pip
  requirements/install.pip
  requirements/report.pip
  requirements/test.pip
  setup.py
  tasks/__init__.py
  tasks/helpers.py
  tasks_helpers.py
Labels: build, update

#2336 Upgrade mongo update
  .circleci/config.yml
  CHANGELOG.md
  docker-compose.test.yml
  docker-compose.yml
  docs/system-dependencies.md
  requirements/install.pip
  udata/core/dataset/models.py
Labels: update

#2104 Celery 4.3 - Redis 3.2
  requirements/install.pip
Labels: update

#2345 Disallow URLs in first and last names
  js/locales/udata.en.json
  requirements/install.pip
  udata/auth/forms.py
  udata/core/user/forms.py
  udata/forms/validators.py
  udata/tests/forms/test_user_forms.py
  udata/translations/udata.pot
Labels: security
