Repository opendatateam/udata, pull requests merged in 2019-05, with the labels that each got.

#2115 Shorter (non-canonical) munin tasks names
  udata/commands/worker.py
Labels: enhancement

#2114 Backport deprecation warnings
  udata/api/__init__.py
  udata/core/activity/api.py
  udata/core/dataset/api.py
  udata/core/dataset/forms.py
  udata/core/discussions/api.py
  udata/core/discussions/forms.py
  udata/core/followers/api.py
  udata/core/issues/api.py
  udata/core/issues/forms.py
  udata/core/jobs/api.py
  udata/core/jobs/forms.py
  udata/core/organization/api.py
  udata/core/organization/forms.py
  udata/core/post/forms.py
  udata/core/reuse/api.py
  udata/core/reuse/forms.py
  udata/core/site/forms.py
  udata/core/tags/api.py
  udata/core/topic/forms.py
  udata/core/user/api.py
  udata/core/user/forms.py
  udata/features/oembed/api.py
  udata/features/territories/api.py
  udata/forms/fields.py
  udata/frontend/helpers.py
  udata/harvest/api.py
  udata/harvest/forms.py
  udata/tests/api/test_auth_api.py
  udata/tests/api/test_base_api.py
  udata/tests/api/test_swagger.py
  udata/tests/api/test_user_api.py
  udata/tests/forms/test_form_field.py
  udata/tests/forms/test_nested_model_list_field.py
  udata/tests/frontend/test_dataset_frontend.py
  udata/tests/frontend/test_organization_frontend.py
  udata/tests/frontend/test_reuse_frontend.py
  udata/tests/frontend/test_user_frontend.py
  udata/tests/test_linkchecker.py
Labels: bug, enhancement

#2113 Metrics cleanup
  CHANGELOG.md
  udata/core/dataset/factories.py
  udata/core/metrics/__init__.py
  udata/core/metrics/commands.py
  udata/core/metrics/models.py
  udata/core/metrics/registry.py
  udata/core/metrics/signals.py
  udata/core/metrics/specs.py
  udata/core/metrics/tasks.py
  udata/core/site/metrics.py
  udata/tests/api/test_metrics_api.py
  udata/tests/site/test_site_metrics.py
  udata/tests/test_metrics.py
Labels: performance, refactoring, security

#2124 Export multiple models objects to CSV (dataset of datasets)
  docs/adapting-settings.md
  udata/core/dataset/csv.py
  udata/core/dataset/tasks.py
  udata/core/tags/__init__.py
  udata/models/__init__.py
  udata/settings.py
  udata/tests/dataset/test_dataset_tasks.py
Labels: enhancement

#2125 [admin] delete a single comment in a discussion
  CHANGELOG.md
  js/components/discussions/modal.vue
  udata/core/discussions/api.py
  udata/tests/test_discussions.py
Labels: admin, enhancement

#2131 Harvest sources list API fix
  CHANGELOG.md
  udata/core/dataset/tasks.py
  udata/core/metrics/tasks.py
  udata/harvest/models.py
  udata/migrations/2019-05-09-harvest-items-deleted-datasets.js
Labels: api, bug, harvesting, performance

#2148 fix display consistency of cards for reuses inside topic pages
  CHANGELOG.md
  udata/templates/topic/display.html
Labels: user experience, user-interface

#2166 fluidify search results
  CHANGELOG.md
  udata/templates/macros/paginator.html
  udata/templates/search.html
Labels: bug, user experience, user-interface
