Repository opendatateam/udata, pull requests merged in 2019-01, with the labels that each got.

#1961 Feature/clean user extras on delete
  udata/core/user/models.py
Labels: bug, enhancement

#1956 Data migrations v2
  .circleci/config.yml
  CHANGELOG.md
  package.json
  udata/commands/db.py
  udata/entrypoints.py
  udata/migrations/2015-05-06-migrate-issues.js
  udata/migrations/2015-06-10-public-service-to-badges.js
  udata/migrations/2015-08-19-migrate-resource-published.js
  udata/migrations/2015-09-14-generic-badges.js
  udata/migrations/2015-09-23-community-resources.js
  udata/migrations/2015-09-25-migrate-harvest-sources-validation.js
  udata/migrations/2015-10-08-migrate-resources-field-names.js
  udata/migrations/2015-10-19-deduplicate-badges.js
  udata/migrations/2015-11-16-remove-supplier.js
  udata/migrations/2015-11-23-set-uuid-as-community-resources-id.js
  udata/migrations/2015-12-09-generic-references.js
  udata/migrations/2016-01-12-add-tag-slug.js
  udata/migrations/2016-01-21-set-uuid-for-community-resources.js
  udata/migrations/2016-01-21-set-uuid-for-resources.js
  udata/migrations/2016-01-25-fix-resources-checksums.js
  udata/migrations/2016-02-03-clean-topic-datasets.js
  udata/migrations/2016-03-02-fix-resources-checksums.js
  udata/migrations/2016-06-24-rename-granularities.js
  udata/migrations/2016-11-08-truncate-tags.js
  udata/migrations/2016-11-28-deduplicate-users.js
  udata/migrations/2016-11-29-confirm-active-users.js
  udata/migrations/2016-12-20-dublin-core-frequencies.js
  udata/migrations/2017-01-05-geozones-admin-levels.js
  udata/migrations/2017-02-23-references-indexes.js
  udata/migrations/2017-02-25-missing-user-metrics.js
  udata/migrations/2017-03-06-fix-harvesters-owners.js
  udata/migrations/2017-04-24-fix-resources-urls.js
  udata/migrations/2017-07-07-deduplicate-org-members.js
  udata/migrations/2017-10-05-purge-void-resources.js
  udata/migrations/2017-10-11-deduplicate-discussions.js
  udata/migrations/2017-10-16-fix-switched-temporal-coverage.js
  udata/migrations/2017-10-24-cleanup-resources-checksum.js
  udata/migrations/2018-02-12-authlib.js
  udata/migrations/2018-02-13-migrate-resources-api-filetype.js
  udata/migrations/2018-03-14-geozones-validity.js
  udata/migrations/2018-04-03-normalize-resource-format.js
  udata/migrations/2018-05-04-remove-userupdateddataset-activities.js
  udata/migrations/2018-06-07-community-resources-remove-references-to-deleted-datasets.js
  udata/migrations/2019-06-07-posts-publication-date.js
  udata/migrations/__init__.py
  udata/tests/cli/test_db_cli.py
  udata/tests/plugin.py
  udata/tests/test_migrations.py
Labels: documentation, enhancement, refactoring, to-be-discussed

#1991 Resource form, modal and workflow fixes
  CHANGELOG.md
  js/components/dataset/resource/add-modal.vue
  js/components/dataset/resource/form.vue
  js/components/dataset/resource/modal.vue
  js/locales/udata.en.json
  js/locales/udata.fr.json
  js/mixins/uploader.js
  js/mixins/watch-refs.js
  js/views/community-resource-wizard.vue
  js/views/dataset-wizard.vue
Labels: admin, bug, enhancement, user experience

#1993 Added missing number input
  CHANGELOG.md
  js/components/form/base-field.js
  js/components/form/base-form.js
  js/components/form/number-input.vue
  specs/components/form/fields.specs.js
Labels: admin, bug, user experience

#1994 Fix the organization private datasets and reuses counters
  CHANGELOG.md
  udata/templates/organization/display.html
Labels: bug

#1995 Disable autocorrect, spellcheck... on search and completion fields
  CHANGELOG.md
  js/components/form/base-completer.vue
  js/components/site-search.vue
Labels: bug, user experience

#1996 Fix harvest preview in edit form not taking configuration (features and filters)
  CHANGELOG.md
  js/components/harvest/config-form.vue
  js/components/harvest/feature-field.vue
  js/components/harvest/filter-field.vue
  js/views/harvester-edit.vue
Labels: admin, bug, harvesting

#1997 Ensure organization page react to URL hash changes
  CHANGELOG.md
  js/front/organization/index.js
Labels: bug

#2000 Form fixes
  CHANGELOG.md
  js/components/dataset/form.vue
  js/components/dataset/resource/add-modal.vue
  js/components/dataset/resource/form.vue
  js/components/dataset/resource/modal.vue
  js/components/form/base-field.js
  js/components/form/base-form.js
  js/components/form/horizontal-field.vue
  js/components/form/horizontal-form.vue
  js/components/form/vertical-field.vue
  js/components/harvest/form.vue
  js/components/organization/form.vue
  js/components/reuse/form.vue
  js/components/user/form.vue
  js/components/widgets/wizard.vue
  js/locales/udata.en.json
  js/locales/udata.fr.json
  js/models/communityresource.js
  js/models/dataset.js
  js/models/harvest/source.js
  js/models/me.js
  js/models/organization.js
  js/models/reuse.js
  js/models/user.js
  js/pubsub.js
  js/utils.js
  js/views/dataset-edit.vue
  js/views/dataset-wizard.vue
  js/views/harvester-edit.vue
  js/views/harvester-wizard.vue
  js/views/me-edit.vue
  js/views/organization-edit.vue
  js/views/organization-wizard.vue
  js/views/reuse-edit.vue
  js/views/reuse-wizard.vue
  js/views/user-edit.vue
Labels: admin, bug, user experience

#2002 New translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.pt.json
  udata/translations/pt/LC_MESSAGES/udata.po
Labels: i18n

#2003 New translations udata.en.json (French)
  js/locales/udata.fr.json
Labels: i18n

#2005 Improve API errors handling and visual feedback for unauthorized actions
  CHANGELOG.md
  js/admin.vue
  js/components/dataset/delete-modal.vue
  js/components/dataset/restore-modal.vue
  js/components/discussions/modal.vue
  js/components/form/base-field.js
  js/components/harvest/delete-modal.vue
  js/components/harvest/mappings-form.vue
  js/components/harvest/preview.vue
  js/components/harvest/schedule-modal.vue
  js/components/harvest/validation-modal.vue
  js/components/organization/delete-modal.vue
  js/components/organization/member-modal.vue
  js/components/organization/members.vue
  js/components/organization/restore-modal.vue
  js/components/post/delete-modal.vue
  js/components/post/publish-modal.vue
  js/components/post/unpublish-modal.vue
  js/components/reuse/delete-modal.vue
  js/components/topic/delete-modal.vue
  js/components/transfer/request-modal.vue
  js/components/transfer/response-modal.vue
  js/components/user/apikey.vue
  js/components/user/delete-me-modal.vue
  js/locales/udata.en.json
  js/models/organization.js
  js/views/editorial.vue
  js/views/organization.vue
  js/views/post-edit.vue
Labels: admin, bug, user experience

#2006 Expose license alternate titles and urls
  CHANGELOG.md
  udata/core/dataset/api_fields.py
  udata/core/dataset/commands.py
Labels: bug, enhancement

#2008 New translations
  js/locales/udata.ar.json
  js/locales/udata.es.json
  js/locales/udata.fr.json
  js/locales/udata.pt.json
Labels: i18n
