Repository opendatateam/udata, pull requests merged in 2019-04, with the labels that each got.

#2098 Tracking blacklist fixes
  CHANGELOG.md
  udata/settings.py
Labels: bug, performance

#2102 Bubble up uploader errors - fix #2101
  CHANGELOG.md
  js/components/dataset/resource/modal.vue
  js/mixins/uploader.js
Labels: admin, bug

#2103 Fix munin zeros
  CHANGELOG.md
  docs/administrative-tasks.md
  udata/commands/worker.py
  udata/tasks.py
Labels: bug, performance

#2110 New Crowdin translations
  udata/translations/sr/LC_MESSAGES/udata.po
Labels: i18n
